### ISSUE TITLE
Does this package support Request interceptor?

### ISSUE THREAD

**Issue by juzhiyuan** [samber/prometheus-query-js#12]
Hi,

Thanks to this project & your contribution! When I introduce this package to our product, I find that we have some QueryString needed when calling Prometheus.

Just want to know, if this package supports Request Interceptor?

**Comment by samber** [comment]
Hi @juzhiyuan !

Sounds interesting, can you write a PR ?

**Comment by samber** [comment]
@juzhiyuan done

doc: https://github.com/samber/prometheus-query-js#hook-http-requests-and-responses
