### ISSUE TITLE
Use HTTPS-capable prometheus.demo.do.prometheus.io in examples

### ISSUE THREAD

**Issue by bluecmd** [samber/prometheus-query-js#15]
Hi!

As you know http://demo.robustperception.io:9090/ is using HTTP and causes [some issues](https://github.com/samber/chartjs-plugin-datasource-prometheus/blob/412dfe83ffb0e406376db8f8d10b1d2bf4b6fc62/example/main.js#L58-L61) in examples due to that.

May I suggest you use the official demo site instead; https://prometheus.demo.do.prometheus.io in this repository and chartjs-plugin-datasource-prometheus?

**Comment by samber** [comment]
Sure!

Thanks for building this demo environment ;)
