### ISSUE TITLE
Errors of Prometheus are not handled

### ISSUE THREAD

**Issue by lawcha** [samber/prometheus-query-js#18]
# My problem
I execute the query "sensor_1 @ 1234567" , resulting in the following request:
```
GET /query?query=sensor_1+%40+123456&time=1647448589.845
```
If I look to the raw response that Prometheus gives me, this is that I obtain:
```
{
   "status":"error",
   "errorType":"bad_data",
   "error":"@ modifier is disabled"
}
```

However, in my Angular project, the prometheus-query library does not seem to handle the case where there is an error as above (see screenshot below).

![image](https://user-images.githubusercontent.com/71696298/158642338-05f9702d-cb33-481e-a819-e32b0b2251a9.png)

# Question
I think this is a problem of the library itself, as I said. Can someone confirm this and tell me how I can resolve this ? Thank you.

**Comment by lawcha** [comment]
I currently handle this using the `responseInterceptor` defined in the options of the Prometheus driver. The "data" property may be checked to know if an error occurs or not.

NB: The response interceptor may be used in the case of the PR [here](https://github.com/samber/prometheus-query-js/pull/19).

**Comment by samber** [comment]
I released a new version of the library.
