### ISSUE TITLE
Incompatible with node v17

### ISSUE THREAD

**Issue by peterhirn** [samber/prometheus-query-js#21]
Library works perfectly with node `v16.14.2` but returns this error in `v17.8.0`.

```
Unknown error {
  status: 'error',
  errorType: 'unexpected_error',
  error: 'unexpected http error'
}
```

**Comment by samber** [comment]
Did you test with the same version of Axios library?

**Comment by peterhirn** [comment]
Not sure what you mean, I have these (and other) dependencies:

```json
  "dependencies": {
    "axios": "^0.26.1",
    "prometheus-query": "^3.2.1"
  }
```

Does it work for you with node v17?

**Comment by samber** [comment]
It works on my computer with both versions.

```js
npm install
```

Then:

```js
docker run --rm -it  -v `pwd`:/app node:16 bash
docker run --rm -it  -v `pwd`:/app node:17 bash
```

Then:

```js
npm run example
```

**Comment by peterhirn** [comment]
Thanks for testing this! I'll try to reproduce the problem with a minimal project, maybe it's because I'm running node on windows.

**Comment by peterhirn** [comment]
Using node v17.8 requests against `https://prometheus.demo.do.prometheus.io/` work, but fail for `http://localhost:9090/` where I have `prometheus-2.34.0.windows-amd64` running.
