### ISSUE TITLE
Add support for data push

### ISSUE THREAD

**Issue by valyala** [samber/prometheus-query-js#22]
It would be great if the prometheus-query-js would be able to push data to Prometheus-like databases such as [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/). It may push data via any [supported data ingestion protocol](https://docs.victoriametrics.com/#how-to-import-time-series-data). The most straightforward protocol for js is [JSON import](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format) or [OpenTSDB HTTP /put protocol](https://docs.victoriametrics.com/#sending-opentsdb-data-via-http-apiput-requests), which is also based on JSON.

**Comment by samber** [comment]
I'm not sure this library should offer such API.

`prometheus-query-js` has been built for querying prometheus-like TSDB (read-only).

The community built a lot of libraries for exporting metrics. Why not implement such a feature in those libs?

Can you argue on that?
