### ISSUE TITLE
String parameter for rangeQuery step?

### ISSUE THREAD

**Issue by tredondo** [samber/prometheus-query-js#23]
The [rangeQuery](https://github.com/samber/prometheus-query-js/blob/master/src/driver.ts#L198) method only accepts a numeric parameter for step.

But [the documentation says](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries)

    step=<duration | float>: Query resolution step width **in duration format or** float number of seconds.

The duration format is a string, and can go as low as `1ms`.

**Comment by Dorbash** [comment]
I agree with @tredondo, prometheus is limited with seconds when it comes to big numbers.
For example, query directly via the API with step of 1 week works well with `1w` but doesn't work with `604,800s` which is the same period in seconds. Therefore, there must be a way of passing it as a parameter.

**Comment by samber** [comment]
Thanks for your feedback.

I made a fix in v3.3.0 ;)
