### ISSUE TITLE
How to set the rate interval in the PROMQL similar to $__rate_interval by grafana.

### ISSUE THREAD

**Issue by thechromosomes** [samber/prometheus-query-js#35]
I am trying to fetch the different metrics using PROMQL and make my custom dashboard similar to grafana. But I am not sure how to dynamically set rate interval and step in query range using the given time range.

I am using HTTP API provided by the Prometheus.

```
> const rateInterval = "5m"; **//need to make this dynamic according to the given time range.**
> const queryRangeList = {
>   load15: `node_load15`,
>   cpuUsage: `sum by(instance) (irate(node_cpu_seconds_total{instance="localhost:9100",job="node", mode="system"}[${rateInterval}])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance="localhost:9100",job="node"}[${rateInterval}])))`,
>   memoryUsage: `node_memory_MemTotal_bytes{instance="localhost:9100",job="node"} - node_memory_MemFree_bytes{instance="localhost:9100",job="node"} - (node_memory_Cached_bytes{instance="localhost:9100",job="node"} + node_memory_Buffers_bytes{instance="localhost:9100",job="node"} + node_memory_SReclaimable_bytes{instance="localhost:9100",job="node"})`,
> };
> 
> module.exports = {
>   queryRangeList,
> }
```

**Comment by samber** [comment]
I think this is a general question, not linked to this specific library.

You can try something like:

```js
function generateQueries(rateInterval) {
   return {
      load15: `node_load15`,
      cpuUsage: `sum by(instance) (irate(node_cpu_seconds_total{instance="localhost:9100",job="node", mode="system"}[${rateInterval}])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance="localhost:9100",job="node"}[${rateInterval}])))`,
      memoryUsage: `node_memory_MemTotal_bytes{instance="localhost:9100",job="node"} - node_memory_MemFree_bytes{instance="localhost:9100",job="node"} - (node_memory_Cached_bytes{instance="localhost:9100",job="node"} + node_memory_Buffers_bytes{instance="localhost:9100",job="node"} + node_memory_SReclaimable_bytes{instance="localhost:9100",job="node"})`,
  };
}
```

**Comment by thechromosomes** [comment]
> I think this is a general question, not linked to this specific library.
> 
> You can try something like:
> 
> ```js
> function generateQueries(rateInterval) {
>    return {
>       load15: `node_load15`,
>       cpuUsage: `sum by(instance) (irate(node_cpu_seconds_total{instance="localhost:9100",job="node", mode="system"}[${rateInterval}])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance="localhost:9100",job="node"}[${rateInterval}])))`,
>       memoryUsage: `node_memory_MemTotal_bytes{instance="localhost:9100",job="node"} - node_memory_MemFree_bytes{instance="localhost:9100",job="node"} - (node_memory_Cached_bytes{instance="localhost:9100",job="node"} + node_memory_Buffers_bytes{instance="localhost:9100",job="node"} + node_memory_SReclaimable_bytes{instance="localhost:9100",job="node"})`,
>   };
> }
> ```

Here, the question is the **rateInterval** provided as params. how to calculate this interval dynamically. using given **time range** and **step**.

**Comment by samber** [comment]
oh! i see

Rate interval and step can be set independently. Rate interval could eventually be greater than or equal to step.

```
Step = (time frame end - time frame start) / 100 data points
Rate interval = step
```

Prometheus supports up to 11.000 data points per query. But most of time, such accuracy is pointless.
